FROM python:2.7

WORKDIR /usr/src/app

RUN set -ex; \
    \
    apt-get update \
    && apt-get install -y \
      git \
      libspatialindex-dev \
    ; \
    git clone https://github.com/mapc/rental-listing-geolocator . \
    ; \
    pip install \
      rtree \
      'scipy==0.19.1' \
      pandas \
      shapely \
      requests \
      geopandas \
      matplotlib 
