FROM python

WORKDIR /usr/src/app

RUN set -ex; \
    \
    apt-get update \
    && apt-get install -y \
      git \
    ; \
    git clone https://github.com/mapc/rental-listing-mapper . \
    && chmod +x map \
    ; \
    pip install \
      pandas \
      psycopg2 \
      sqlalchemy 
