version: '3'

services:

  cleaner:
    build:
      context: .
      dockerfile: Dockerfile.cleaner

    volumes:
      - ./volumes/cleaner/csv/:/opt/files
      - ./volumes/cleaner/output:/opt/output
      - ./volumes/cleaner/spatial:/opt/spatial

    command: ["Rscript", "main.R"]

    environment:
      - CODE_PATH=/usr/src/app
      - SPATIAL_SRC_PATH=/opt/spatial
      - OUT_FILE_PATH=/opt/output
      - IN_FILE_PATH=/opt/files
      - IN_FILE_NAME=mapped.csv
      - IN_GEO_NAME=170726_padmapper_sample_2.csv


  geolocator:
    build:
      context: .
      dockerfile: Dockerfile.geolocator

    volumes:
      - ./volumes/geolocator/data:/opt/files
      - ./volumes/geolocator/output:/opt/output

    command: ['python', '-u', 'geolocation_validation.py']

    env_file:
      - ./.env.geolocator


  mapper:
    build:
      context: .
      dockerfile: Dockerfile.mapper

    volumes:
      - ./volumes/cleaner/csv:/opt/files

    command: ["./map"]

    environment:
      - OUT_FILE_PATH=/opt/files
      - OUT_FILE_NAME=mapped.csv
