version: '3'

services:

  cleaner:
    build:
      context: .
      dockerfile: Dockerfile.cleaner

    volumes:
      - ./volumes/cleaner/csv/:/opt/files
      - ./volumes/cleaner/output:/opt/output
      - ./volumes/cleaner/spatial:/opt/spatial

    command: ["Rscript", "main.R"]

    environment:
      - CODE_PATH=/usr/src/app
      - SPATIAL_SRC_PATH=/opt/spatial
      - OUT_FILE_PATH=/opt/output
      - DEBUG_FILE=debug.csv
      - IN_FILE_PATH=/opt/files
      - IN_FILE_NAME=mapped.csv


  geolocator:
    build:
      context: .
      dockerfile: Dockerfile.geolocator

    volumes:
      - ./volumes/geolocator/data:/opt/files
      - ./volumes/geolocator/output:/opt/output

    command: ['python', '-u', 'geolocation_validation.py']

    environment:
      - GDAL_DATA=/usr/share/gdal
      - data_path=/opt/files
      - output_path=/opt/output
      - chart_path=/opt/output/charts
      - analysis_path=/opt/output/analysis
      - worker_folder=/opt/files/worker_data
      - worker_proc=/opt/files/worker_processed
      - mapc_path=CSV/mapc
      - csv_path=CSV
      - point_path=Points

  mapper:
    build:
      context: .
      dockerfile: Dockerfile.mapper

    volumes:
      - ./volumes/cleaner/csv:/opt/files

    command: ["./map"]

    env_file:
      - ./.env.mapper
